# Generated by Django 3.1.4 on 2021-01-02 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_trial', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='emp_id',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='lastname',
        ),
        migrations.AddField(
            model_name='employee',
            name='inputs',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
